services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Устанавливаем фактор репликации в 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # Для транзакционных топиков
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # Минимальное количество реплик
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Используем только один слушатель для Docker сети
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper


  orders-service:
    build: /Users/artemka/IdeaProjects/orders-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  payment-service:
    build: /Users/artemka/IdeaProjects/payment-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  shipping-service:
    build: /Users/artemka/IdeaProjects/Shipping
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  notifications-service:
    build: /Users/artemka/IdeaProjects/Notifications
    ports:
      - "8083:8083"
    depends_on:
      - kafka

